config/routes.rb
Rails.application.routes.draw do

devise_for :users, controllers: {
  registrations: 'users/registrations'
}

resources :users, only: [:index,:show,:edit]

resources :users do
  collection do
    get 'mypage'
  end
end

# after
root 'items#index'
resources :cards, only: [:index, :show, :new]
resources :items, only: [:index, :show, :new, :edit, :update] do

  collection do
    get 'get_category_children', defaults: {format: 'json'}
    get 'get_category_grandchildren', defaults: {format: 'json'}
  end
end

  resources :cards, only: [:index, :show, :new, :create, :destroy]





  resources :logout,only: [:index]

  resources :items do
      member do
      get 'confirm'
      get 'purchase'
      end
    end
  end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  #パスワードは7文字以上制限をかける
  validates :nickname, presence: true
  validates :password, presence: true,length: { minimum: 7 }
  validates :email, presence: true

  has_many :items
  has_one :credit_card

  has_one :profile
  has_one :address
  accepts_nested_attributes_for :profile, allow_destroy: true
  accepts_nested_attributes_for :address, allow_destroy: true

end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController


  def new
    @user = User.new
    @user.build_profile
    @user.build_address
  end

  # POST /resource
  def create
    @user = User.new(user_params)
  if @user.save
      sign_in(@user)
      flash[:alert] = 'ようこそ！ アカウントが登録されました'
      redirect_to root_path
  else
    flash[:alert] = '必須事項を入力してください。'
    redirect_to controller: :registrations, action: :new
  end
  end

  private

  def user_params
    #params[:user][:profile_attributes][:birthday] = params[:birthday]["birthday(1i)"] + "-" + params[:birthday]["birthday(2i)"] + "-" + params[:birthday]["birthday(3i)"]
    params.require(:user).permit(:nickname, :email, :password,profile_attributes: [:first_name, :family_name, :first_name_kana, :family_name_kana, :birth_day, :birth_month, :birth_year],address_attributes: [:post_code, :prefecture_id, :city, :house_number, :building_name, :telephone_number,])
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
  end


  def show
    @user = User.new
  end

  def logout
  end
  
  def profile   
  end

  def profile_update
    if @user.update(user_params)
      redirect_to user_path
    else
      render :profile
    end
  end

  def mypage
  end

  private

  def user_params
    params.require(:user).permit(:nickname, :email, :password)
  end

  def profile_params
    params.require(:profile).permit(:first_name, :family_name, :first_name_kana, :family_name_kana, :birth_year, :birth_month, :birth_day)

  end

  def address_params
    params.require(:address).permit(:post_cord, :prefecture_id, :city, :building_name, :house_number, :telephone_number)
  end


end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_footer.html.haml
.footer
  .info
    %ul
      .info--title
        %li FURIMAについて
      .info--content
        %li
          =link_to "会社概要"
        %li
          =link_to "プライバシーポリシー"
        %li
          =link_to "FURIMA利用規約"
        %li
          =link_to "ポイントに関する特約"
    %ul
      .info--title
        %li FURIMAをみる
      .info--content
        %li
          =link_to "カテゴリー一覧"
        %li
          =link_to "ブランド一覧"
    %ul
      .info--title
        %li ヘルプ＆ガイド
      .info--content
        %li
          =link_to "FURIMAガイド"
        %li
          =link_to "FURIMAロゴ利用ガイドライン"
        %li
          =link_to "お知らせ"

  .logo
    =link_to do
      = image_tag "/assets/logo/logo-white.png",size: "200x60", alt: "visual-1"
    %p © FURIMA

app/views/users/_header.html.haml
.header
  .header__top
    = link_to root_path, class:"header__top--rogo" do
      = image_tag "/logo.png", size: "180x54", alt: "logo"
    .header__top--form
      %form{action: "/", method: "post"}
        %input{name: "search", size: "40", class:"input", placeholder: "キーワードから探す"}
        %input{type: "submit", value: "検索", class: "btn"}

  .header__bottom
    .header__bottom--left
      %ul.contents
        %li.content
          = link_to do
            %p カテゴリー
          %ul.nav
            %li
              = link_to do
                レディース
              %ul.nav__content
                %li
                  = link_to do
                    トップス
                %li
                  = link_to do
                    ボトムス
                %li
                  = link_to do
                    シューズ
            %li
              = link_to do
                メンズ

            %li
              = link_to do
                キッズ


        %li.content
          = link_to class: "brand" do
            %p ブランド
          %ul.nav
            %li
              = link_to do
                レディース
              %ul.nav__content
                %li
                  = link_to do
                    トップス
                %li
                  = link_to do
                    ボトムス
                %li
                  = link_to do
                    シューズ
            %li
              = link_to do
                メンズ

            %li
              = link_to do
                キッズ

    .header__bottom--right
      - if user_signed_in?
        =link_to user_path(current_user.id), class: "mypage" do
          %p マイページ
      - else
        = link_to new_user_session_path class: "login" do
          %p ログイン
        = link_to users_path class: "signin" do
          %p 新規会員登録

app/views/users/_side.html.haml
.side
  %nav.mypage-menu
    %ul.mypage-menu-list
      %li.mypage-menu-list__item--info
        = link_to "マイページ", class: 'btn'
      %li.mypage-menu-list__item
        = link_to "お知らせ", class: 'btn'
      %li.mypage-menu-list__item
        = link_to "やることリスト", class: 'btn'
      %li.mypage-menu-list__item
        = link_to "いいね！一覧", class: 'btn'
      %li.mypage-menu-list__item
        = link_to "出品する", class: 'btn'
      %li.mypage-menu-list__item
        = link_to "下書き一覧", class: 'btn'
      %li.mypage-menu-list__item
        = link_to "出品した商品-出品中", class: 'btn'
      %li.mypage-menu-list__item
        = link_to "出品した商品-取引中", class: 'btn'
      %li.mypage-menu-list__item
        = link_to "出品した商品-売却済み", class: 'btn'
      %li.mypage-menu-list__item
        = link_to "購入した商品-取引中", class: 'btn'
      %li.mypage-menu-list__item
        = link_to "購入した商品-過去の取引", class: 'btn'
      %li.mypage-menu-list__item
        = link_to "ニュース一覧", class: 'btn'
      %li.mypage-menu-list__item
        = link_to "評価一覧", class: 'btn'
      %li.mypage-menu-list__item
        = link_to "ガイド", class: 'btn'
      %li.mypage-menu-list__item
        = link_to "お問い合わせ", class: 'btn'
    %h3.mypage-menu-list__head
      設定
    %ul.mypage-menu-list--personal
      %li.mypage-menu-list__item
        = link_to "プロフィール", class: 'btn'
      %li.mypage-menu-list__item
        = link_to "発送元・お届け先住所変更",edit_user_path, class: 'btn'
      - if user_signed_in?
        %li.mypage-menu-list__item
          = link_to "支払い方法", new_card_path(current_user.card),class: 'btn'
      - else
        %li.mypage-menu-list__item
          = link_to "支払い方法", new_card_path,class: 'btn'
      %li.mypage-menu-list__item
        = link_to "メール/パスワード", class: 'btn'
      %li.mypage-menu-list__item
        = link_to "本人情報",edit_user_path, class: 'btn'
      %li.mypage-menu-list__item
        = link_to "電話番号の確認", class: 'btn'
      %li.mypage-menu-list__item
        -# 一時的にコメントアウト　下
        -# = link_to "ログアウト",logout_index_path(current_user.id), class: 'btn'

app/views/users/edit.html.haml
.edit-page
  .main
    .address-side
      %nav.mypage-menu
        %ul.mypage-menu-list
          %li.mypage-menu-list__item--info
            = link_to "マイページ", class: 'btn'
          %li.mypage-menu-list__item
            = link_to "お知らせ", class: 'btn'
          %li.mypage-menu-list__item
            = link_to "やることリスト", class: 'btn'
          %li.mypage-menu-list__item
            = link_to "いいね！一覧", class: 'btn'
          %li.mypage-menu-list__item
            = link_to "出品する", class: 'btn'
          %li.mypage-menu-list__item
            = link_to "下書き一覧", class: 'btn'
          %li.mypage-menu-list__item
            = link_to "出品した商品-出品中", class: 'btn'
          %li.mypage-menu-list__item
            = link_to "出品した商品-取引中", class: 'btn'
          %li.mypage-menu-list__item
            = link_to "出品した商品-売却済み", class: 'btn'
          %li.mypage-menu-list__item
            = link_to "購入した商品-取引中", class: 'btn'
          %li.mypage-menu-list__item
            = link_to "購入した商品-過去の取引", class: 'btn'
          %li.mypage-menu-list__item
            = link_to "ニュース一覧", class: 'btn'
          %li.mypage-menu-list__item
            = link_to "評価一覧", class: 'btn'
          %li.mypage-menu-list__item
            = link_to "ガイド", class: 'btn'
          %li.mypage-menu-list__item
            = link_to "お問い合わせ", class: 'btn'
        %h3.mypage-menu-list__head
          設定
        %ul.mypage-menu-list--personal
          %li.mypage-menu-list__item
            = link_to "プロフィール", class: 'btn'
          %li.mypage-menu-list__item
            = link_to "発送元・お届け先住所変更",edit_user_path, class: 'btn'
          %li.mypage-menu-list__item
            = link_to "支払い方法", class: 'btn'
          %li.mypage-menu-list__item
            = link_to "メール/パスワード", class: 'btn'
          %li.mypage-menu-list__item
            = link_to "本人情報", class: 'btn'
          %li.mypage-menu-list__item
            = link_to "電話番号の確認", class: 'btn'
          %li.mypage-menu-list__item
            = link_to "ログアウト",logout_index_path(current_user.id), class: 'btn'
    .address-form
      .content__header
        発送元・お届け先住所変更
      .content__body
        = form_for @users,new_user_path, method: :patch do |f|
          .content__body-title
            .content__body-titlename
              お名前
            .content__body-necessary
              必須
          .content__body-box
            = f.text_field :family_name, class: 'input-form',placeholder: '例） 山田'
          .content__body-box
            = f.text_field :first_name, class: 'input-form',placeholder: '例） 彩'
          .content__body-title
            .content__body-titlename
              お名前カナ
            .content__body-necessary
              必須
          .content__body-box
            = f.text_field :family_name_kana, class: 'input-form',placeholder: '例） ヤマダ'
          .content__body-box
            = f.text_field :first_name_kana, class: 'input-form',placeholder: '例） アヤ'
          .content__body-title
            .content__body-titlename
              郵便番号
            .content__body-necessary
              必須
          .content__body-box
            = f.text_field :post_code, class: 'input-form',placeholder: '例） 1234567'
          .content__body-title
            .content__body-titlename
              都道府県
            .content__body-necessary
              必須
          .content__body-box
            = f.collection_select :prefecture_id, Prefecture.all, :id, :name
          .content__body-title
            .content__body-titlename
              市区町村
            .content__body-necessary
              必須
          .content__body-box
            = f.text_field :city, class: 'input-form',placeholder: '例） 横浜市緑区'
          .content__body-title
            .content__body-titlename
              番地
            .content__body-necessary
              必須
          .content__body-box
            = f.text_field :house_number, class: 'input-form',placeholder: '例） 青山1-1-1'
          .content__body-title
            .content__body-titlename
              建物名
            .content__body-unnecessary
              任意
          .content__body-box
            = f.text_field :building_name, class: 'input-form',placeholder: '例） 柳ビル103'
          .content__body-title
            .content__body-titlename
              電話
            .content__body-unnecessary
              任意
          .content__body-box
            = f.text_field :telephone_number, class: 'input-form',placeholder: '例） 09012345678'

        .content__footer
          = f.submit "変更する",class: "change-btn"
      .itembtn
        =link_to new_item_path do
          .linkBtn
            %p 出品する
            = image_tag '/icon/icon_camera.png',height: "50px", width: "50px", alt: 'sell'
        
= render "/items/footer"

  

app/views/users/index.html.haml
.account-page__inner
  .account-page__inner-header
    = link_to root_path do
      = image_tag "/logo.png", size: "180x54", alt: "logo"
  .account-page__inner-body
    .account-page__inner-body-box
      .account-page__inner-body-title
        新規会員登録
      .account-page__inner-body-tool
        .account-page__inner-body-tool-mail
          = link_to "メールアドレスで登録する", new_user_registration_path, class: "mail_btn"
        .account-page__inner-body-tool-google
          = link_to  "Googleで登録する", "/",class: "google-btn"
        .account-page__inner-body-tool-facebook
          = link_to "Facebookで登録する", "/",class: "facebook-btn"
        .account-page__inner-body-tool-apple
          = link_to "Appleで登録する", "/",class: "apple-btn"
        .account-page__inner-body-comment
          登録することで、
          = link_to "利用規約", root_path 
          と
          = link_to "プライバシーポリシー", root_path 
          に
        .account-page__inner-body-comment2
          同意したものとみなされます。
  .account-page__inner-footer
    .account-page__inner-footer-policy
      .account-page__inner-footer-policy-privacy
        =link_to root_path do
          プライバシーポリシー
      .account-page__inner-footer-policy-kiyaku
        =link_to root_path do
          アプリ利用規約
      .account-page__inner-footer-policy-tokusyo
        =link_to root_path do
          特定商取引に関する表記 
    .account-page__inner-footer-logo
      =link_to root_path, class: "footer-logo" do
        %i.fa.fa-lightburb
    .account-page__inner-footer-incline
      =link_to root_path do
        = image_tag "/logo-white.png",size: "200x60", alt: "visual-1"
    %p © FURIMA

app/views/users/show.html.haml
- breadcrumb :mypage
.wrapper
  = render "header"
.body-mypage
  .mypage-side
    %ul.mypage-menu-list
      %li.mypage-menu-list__item--info
        = link_to "マイページ", class: 'btn'
      %li.mypage-menu-list__item
        = link_to "お知らせ", class: 'btn'
      %li.mypage-menu-list__item
        = link_to "やることリスト", class: 'btn'
      %li.mypage-menu-list__item
        = link_to "いいね！一覧", class: 'btn'
      %li.mypage-menu-list__item
        = link_to "出品する", class: 'btn'
      %li.mypage-menu-list__item
        = link_to "下書き一覧", class: 'btn'
      %li.mypage-menu-list__item
        = link_to "出品した商品-出品中", class: 'btn'
      %li.mypage-menu-list__item
        = link_to "出品した商品-取引中", class: 'btn'
      %li.mypage-menu-list__item
        = link_to "出品した商品-売却済み", class: 'btn'
      %li.mypage-menu-list__item
        = link_to "購入した商品-取引中", class: 'btn'
      %li.mypage-menu-list__item
        = link_to "購入した商品-過去の取引", class: 'btn'
      %li.mypage-menu-list__item
        = link_to "ニュース一覧", class: 'btn'
      %li.mypage-menu-list__item
        = link_to "評価一覧", class: 'btn'
      %li.mypage-menu-list__item
        = link_to "ガイド", class: 'btn'
      %li.mypage-menu-list__item
        = link_to "お問い合わせ", class: 'btn'
    %h3.mypage-menu-list__head
      設定
    %ul.mypage-menu-list--personal
      %li.mypage-menu-list__item
        = link_to "プロフィール", class: 'btn'
      %li.mypage-menu-list__item
        = link_to "発送元・お届け先住所変更", class: 'btn'
      %li.mypage-menu-list__item
        = link_to "支払い方法",new_card_path, class: 'btn'
      %li.mypage-menu-list__item
        = link_to "メール/パスワード", class: 'btn'
      %li.mypage-menu-list__item
        = link_to "本人情報",edit_user_path, class: 'btn'
      %li.mypage-menu-list__item
        = link_to "電話番号の確認", class: 'btn'
      %li.mypage-menu-list__item
        = link_to "ログアウト",logout_index_path(current_user.id), class: 'btn'

  .mypage-main
    %main.container.clearfix
      .contents2
        %section.mypage2
          %figure
            .mypage__icon
              = image_tag 'member_photo_noimage_thumb.png', height: '60', width: '60', class: "mypage__icon__link"
            %h2.mypage__nickname
              = current_user.nickname
            .mypage__number
              .mypage__number--assess
                評価 ０
              .mypage__number--displays
                出品数 ０
        %section.mypage-container
          %ul.mypage-container__tabs
            %li.mypage-container__tabs--notice
              %h3
                = link_to "お知らせ", class: 'btn'
            %li.mypage-container__tabs--todo
              %h3
                = link_to "やることリスト", class: 'btn'
    
          .mypageContents
            %ul.mypageContentsList
              %li.mypageContentsList--link
                %figure
                  .mypageContentsList--link__icon
                    = image_tag 'icon_brand.png', height: '48', width: '48', class: "mypage__tabs--content__link--icon"
                  .mypageContentsList--link__body
                    .mypageContentsList--link__text もう購入しましたか？今なら"+20%還元"
              %li.mypageContentsList--link
                %figure
                  .mypageContentsList--link__icon
                    = image_tag 'icon_brand.png', height: '48', width: '48', class: "mypage__tabs--content__link--icon"
                  .mypageContentsList--link__body
                    .mypageContentsList--link__text 《出品するだけ》最大1,000円分のポイントをもらえる！キャンペーン詳細はこちら！
              %li.mypageContentsList--link
                %figure
                  .mypageContentsList--link__icon
                    = image_tag 'icon_brand.png', height: '48', width: '48', class: "mypage__tabs--content__link--icon"
                  .mypageContentsList--link__body
                    .mypageContentsList--link__text キャッシュレス決済で商品を買うとP1,500もらえる！
              %li.mypageContentsList--link
                %figure
                  .mypageContentsList--link__icon
                    = image_tag 'icon_brand.png', height: '48', width: '48', class: "mypage__tabs--content__link--icon"
                  .mypageContentsList--link__body
                    .mypageContentsList--link__text 「本人確認後」＋「街のお店でのお買い物」でもれなくP1,000をプレゼント！
              %li.mypageContentsList--link
                %figure
                  .mypageContentsList--link__icon
                    = image_tag 'icon_brand.png', height: '48', width: '48', class: "mypage__tabs--content__link--icon"
                  .mypageContentsList--link__body
                    .mypageContentsList--link__text フリマで買うと最大でP5,000+P1,000もらえる！事前準備はこちら
              %li.mypageContentsList--display
                = link_to "一覧を見る", class: 'btn'

        %section.Purchased
          %h2.Purchased__head 購入した商品
          %ul.purchased-tabs
            %li.trade
              %h3
                取引中
            %li
              %h3
                過去の取引
          .tab-contents
            %ul.tab-contents__now
              %li.tab-contents__notfound 取引中の商品がありません
.mypage-footer
  .info
    %ul
      .info--title
        %li FURIMAについて
      .info--content
        %li
          =link_to "会社概要"
        %li
          =link_to "プライバシーポリシー"
        %li
          =link_to "FURIMA利用規約"
        %li
          =link_to "ポイントに関する特約"
    %ul
      .info--title
        %li FURIMAをみる
      .info--content
        %li
          =link_to "カテゴリー一覧"
        %li
          =link_to "ブランド一覧"
    %ul
      .info--title
        %li ヘルプ＆ガイド
      .info--content
        %li
          =link_to "FURIMAガイド"
        %li
          =link_to "FURIMAロゴ利用ガイドライン"
        %li
          =link_to "お知らせ"

  .logo
    =link_to do
      = image_tag "/logo-white.png",size: "200x60", alt: "visual-1"
    %p © FURIMA