config/routes.rb
Rails.application.routes.draw do

devise_for :users, controllers: {
  registrations: 'users/registrations'
}

resources :users, only: [:index,:show,:edit]

resources :users do
  collection do
    get 'mypage'
  end
end

# after
root 'items#index'
resources :cards, only: [:index, :show, :new]
resources :items, only: [:index, :show, :new, :edit, :update] do

  collection do
    get 'get_category_children', defaults: {format: 'json'}
    get 'get_category_grandchildren', defaults: {format: 'json'}
  end
end

  resources :cards, only: [:index, :show, :new, :create, :destroy]





  resources :logout,only: [:index]

  resources :items do
      member do
      get 'confirm'
      get 'purchase'
      end
    end
  end

app/models/item.rb
class Item < ApplicationRecord
  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to_active_hash :prefecture

  has_many :images, dependent: :destroy
  belongs_to :category

  belongs_to :prefecture
  belongs_to :user, optional: true
  

  validates_associated :images
  validates :name, presence: true, length: { maximum: 40 }
  validates :content, presence: true, length: { maximum: 1000 }
  validates :category_id, presence: true
  validates :condition, presence: true
  validates :postage_payer, presence: true
  validates :postage_type, presence: true
  validates :prefecture_id, presence: true
  validates :preparation_day, presence: true
  validates :price, presence: true
  validates :seller_id, presence: true
  validate  :images_number
 
  def images_number
    errors.add(:images, "を1つ以上指定してください") if images.size < 1
    errors.add(:images, "は10個までです") if images.size > 10
  end 
  

  accepts_nested_attributes_for :images, allow_destroy: true


end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:confirm, :show, :destroy, :edit, :update]

  before_action :set_parent_category
  before_action :set_parent_array, only: [:new, :create, :edit, :update]
  require 'payjp'

  def index
    @items = Item.last(4)
    @brandItems = Item.where("brand IS NOT NULL").last(4)
  end

  def new
    @item = Item.new
    @item.images.new
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to root_path, notice: '出品が完了しました'
    else
      flash.now[:alert] = '正しく入力してください。'
      @item.images.new
      set_children_and_grandchildren_array_and_parent_category
      render :new
    end
  end

  def edit
    if current_user && current_user.id != @item.seller_id
      redirect_to root_path
    end
    set_children_and_grandchildren_array_and_parent_category
  end

  def update
    if @item.update(item_params)
      redirect_to root_path
    else
      flash.now[:alert] = '正しく入力してください。'
      set_children_and_grandchildren_array_and_parent_category
      render 'items/edit'
    end
  end

  def destroy
    if @item.destroy
      redirect_to root_path
    else
      redirect_to :show
    end
  end

  def confirm
  end

  def show
    @items = Item.all
    @relatedItems = Item.where(category_id: @item.category_id).where.not(id: params[:id]).order("RAND()").limit(3)
    @seller = User.find_by(id: @item.seller_id)
  end

  def get_category_grandchildren
    @category_grandchildren = Category.find(params[:child_id]).children
  end
  
  def get_category_children
    @category_children = Category.find(params[:parent_id]).children
  end


  # private


  def set_item
    @item = Item.find(params[:id])
  end
  
  def set_parent_array
    @category_parent_array = []
    Category.where(ancestry: nil).each do |parent|
      @category_parent_array << parent
    end
  end

  def set_parent_category
    @parents = Category.where(ancestry: nil)
  end

  def set_children_and_grandchildren_array_and_parent_category
    if @item.category
      @grandchild_category = @item.category
      @child_category = @grandchild_category.parent
      @parent_category = @grandchild_category.root

      @child_category_array = []
      @item.category.parent.siblings.each do |children|
        @child_category_array << children
      end

      @grandchild_category_array = []
      @item.category.siblings.each do |grandchildren|
        @grandchild_category_array << grandchildren
      end
    end
  end

  def purchase
    @item = Item.find(params[:id])
    @card = current_user.credit_card.customer_id
    Payjp.api_key = Rails.application.credentials[:payjp][:PAYJP_SECRET_KEY]
    Payjp::Charge.create(
      amount: @item.price,
      customer: @card,
      currency: 'jpy'
    )
    @item.update( buyer_id: current_user.id)
    redirect_to root_path
    flash[:notice] = '商品の購入が完了しました'
  end

  private

  def item_params
    params.require(:item).permit(:name, :content, :brand, :category_id, :condition, :postage_payer, :postage_type, :prefecture_id, :preparation_day, :price, images_attributes: [:image_url, :_destroy, :id]).merge(seller_id: current_user.id)
  end

end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_header.html.haml
.header
  .header__top
    = link_to root_path, class:"header__top--rogo" do
      = image_tag "/logo.png", size: "180x54", alt: "logo"
    .header__top--form
      %form{action: "/", method: "post"}
        %input{name: "search", size: "40", class:"input", placeholder: "キーワードから探す"}
        %input{type: "submit", value: "検索", class: "btn"}

  .header__bottom
    .header__bottom--left
      %ul.contents
        %li.content.category
          = link_to do
            %p カテゴリー
          %ul.nav
            - @parents.each do |parent|
              %li.parent
                = link_to do
                  = parent.name
                %ul.nav__content
                  .children-backboard
                  - parent.children.each do |child|
                    %li.child-name
                      = link_to do
                        = child.name
                      %ul.nav__content--grandchild
                        .grandchildren-backboard
                        - child.children.each do |grandchild|
                          %li.grandchild-name
                            = link_to do
                              = grandchild.name 
                    
                
        %li.content
          = link_to class: "brand" do
            %p ブランド
         

    .header__bottom--right
      - if user_signed_in?
        =link_to mypage_users_path, class: "mypage" do
          %p マイページ
      - else
        = link_to new_user_session_path, class: "login" do
          %p ログイン
        = link_to users_path, class: "registration" do
          %p 新規会員登録

app/views/items/_item.html.haml
  
= link_to item_path(item) do
  = image_tag item.images.first.image_url.url,class: "product-img"

  - if item.buyer_id.present?
    = render partial: "shared/soldout" 
  .product-content
    .product-content__upper
      = item.name
    %ul.product-content__center
      %li
        = item.price
        円
      %li
        %i.fas.fa-star
        %span
          0
    .product-content__footer
      (税込)

app/views/items/card.html.haml
.main-page
  %main.container.clearfix
    .contents
      .creditContainer
        .creditContainer__head
          クレジットカード情報入力
        .card
          .card__content
            .cardGroup
              %label.cardGroup
                カード番号
              %span.requiredItem
                必須
              %input{type: "text", size: "40", class:"cardNumber", placeholder: "半角数字のみ", maxlengh: "19"}
            %ul.card-list
              %li
                =link_to do
                  = image_tag 'visa-icon.png', alt: 'visa', height: '20', width: '49'
              %li
                =link_to do
                  = image_tag 'master-icon.png', alt: 'master', height: '20', width: '34'
              %li
                =link_to do
                  = image_tag 'saison-icon.svg', alt: 'saison', height: '20', width: '30'
              %li
                =link_to do
                  = image_tag 'jcb-icon.png', alt: 'jcb', height: '20', width: '32'
              %li
                =link_to do
                  = image_tag 'amex-icon.png', alt: 'amex', height: '20', width: '21'
              %li
                =link_to do
                  = image_tag 'diners-icon.gif', alt: 'diners', height: '20', width: '32'
              %li
                =link_to do
                  = image_tag 'discover-icon.png', alt: 'discover', height: '20', width: '32'
            .cardExpiration
              %label.cardExpiration__date
                有効期限
              %span.requiredItem
                必須
              %br
            .monthBox
              %select.monthBox__expire
                %option{value: "01"}
                  01
                %option{value: "02"}
                  02
                %option{value: "03"}
                  03
                %option{value: "04"}
                  04
                %option{value: "05"}
                  05
                %option{value: "06"}
                  06
                %option{value: "07"}
                  07
                %option{value: "08"}
                  08
                %option{value: "09"}
                  09
                %option{value: "10"}
                  10
                %option{value: "11"}
                  11
                %option{value: "12"}
                  12
                %i.fas.fa-chevron-down
              %span
                月
            .yearBox
              %select.yearBox__expire
                %option{value: "20"}
                  20
                %option{value: "21"}
                  21
                %option{value: "22"}
                  22
                %option{value: "23"}
                  23
                %option{value: "24"}
                  24
                %option{value: "25"}
                  25
                %option{value: "26"}
                  26
                %option{value: "27"}
                  27
                %option{value: "28"}
                  28
                %option{value: "29"}
                  29
                %option{value: "30"}
                  30
                %i.fas.fa-chevron-down
              %span
                年
            .securityGroup
              %label.securityGroup__code
                セキュリティコード
              %span.requiredItem
                必須
              %input{type: "text", size: "40", class: "securityGroup__number", placeholder: "カード背面4桁もしくは3桁の番号"}
            .helpNumber
              .helpNumber__text
                %span.helpNumber__text--question
                  ?
                カード裏面の番号とは？
              .securityCode-info
            %button{type: "button", id: "#", class: "btn-add"}
              追加する

app/views/items/confirm.html.haml
.wrapper 
  .confirm-header
    .confirm-header__top-rogo
      = link_to image_tag "/logo.png", size: "185x49", alt: "logo"
  .container
    .products-top
      %h2.products-text
        購入内容の確認
    .products-main
      .products-main__itembox
        = image_tag @item.images.first.image_url.url if@item.images.present?
      .products-main__detail
        .products-main__detail__name
          = @item.name
        .products-main__detail__price
          %span.products-main__detail__price__ja
            送料込み(税込)
          %span.products-main__detail__price__fee
            = "#{@item.price}円"
    .buy
      .buy__content
        .buy__content__price
          %span.buy__content__price__label
            支払い金額
          %span.buy__content__price__cel
            = "#{@item.price}円"
        .buy__content__point
          %span.buy__content__point__input
          %span.buy__content__point__img
            = link_to image_tag "/logo.png", size: "80x18", alt: "logo"
          %span.buy__content__point__label
            ポイント
          %span.buy__content__point__cel
            所持ポイント : P0
    .user-info-pay
      .user-info-pay__box
        %h3.user-info-pay-text
          支払い方法
        %p.user-info-pay-link
          = link_to new_card_path do
            別のカードを登録する
    .user-info-delivery
      .user-info-delivery__box
        %h3.user-info-delivery-text
          配達先
        %p.user-info-delivery-link
          = link_to "配達先を変更する", "#"
    .confirm
      %p.confirm__info-text
        郵便局/コンビニ受取をご希望の方は、購入後に
        %span.products-purchase-bold  取引画面
        から受取場所を変更をすることが可能です。出品者が発送作業を開始した後は受取場所の変更ができませんので、早めに変更を行ってください。
      %p.confirm__text--comment
        この配送先と支払い方法で購入する。
      - if current_user.credit_card.present?
        = link_to "購入する", purchase_item_path, class: "confirm__contact--comment"
      - else
        = link_to "クレジットカードを登録してください。", new_card_path, class: "confirm__contact--comment"
    .mypage_btn
    = link_to mypage_users_path do
      マイページへもどる
  .confirm-footer
    %ul.confirm-footer__name
      %li.footer__name__text
        = link_to "プライバシーポリシー", "#"
      %li.confirm-footer__name__text
        = link_to "フリマ利用規約", "#"
      %li.confirm-footer__name__text
        = link_to "特定商取引に関する表記", "#"
    .confirm-footer__rogo
      = link_to image_tag "/logo.png", size: "80x45", alt: "logo"

app/views/items/edit.html.haml
.wrapper
  .top
    .top__logo
      =link_to root_path do
        = image_tag "/logo.png", size: "180x54", alt: "logo"
  .main
    .form
      = form_for @item do |f|
        = f.hidden_field :seller_id, value: current_user.id
        .content__1
          .image
            .content__header
              %h3 出品画像
              %span 必須
            .image__file#image-box
              #previews
                -if @item.persisted?
                  -@item.images.each_with_index do |image, i|
                    =image_tag image.image_url.url, data:{ index: i }, width: "100", height: '100'
              = f.fields_for :images do |i|
                %div{data:{index: i.index}, class: "js-file_group"}
                  = i.file_field :image_url,item_id: @item.id, class: "js-file"
                  .js-remove
                    %span 削除

                - if @item.persisted?
                  = i.check_box :_destroy, data:{ index: i.index}, class: "hidden-destroy"
              - if @item.persisted?
                %div{data:{index: @item.images.count}, class: "js-file_group"}
                  = file_field_tag :image_url, name: "item[images_attributes][#{@item.images.count}][image_url]", class: 'js-file'
                  .js-remove
                    %span 削除

        .content__2
          .items
            .items__name
              .content__header
                %h3 商品名
                %span 必須
              .items__name--input
                = f.text_field :name, placeholder: "40字まで"
            .items__content
              .content__header
                %h3 商品の説明
                %span 必須
              .input
                = f.text_area :content, row:"10", cols:"50",class:"input__text" ,placeholder: "商品の説明（必須 1000文字以内）色、素材、重さ、定価、注意点など"
        .content__3
          .detail
            %h2 商品の詳細
            .detail--category
              .content__header
                %h3 カテゴリー
                %span 必須
              = f.collection_select :category_id, @category_parent_array,:id, :name, {selected:@parent_category.id, include_blank: "---"},{id: "parent_category", required: true}
              #children_wrapper
                = f.collection_select :category_id, @child_category_array,:id, :name, {selected:@child_category.id, include_blank: "---"},{required: true}
              #grandchildren_wrapper
                = f.collection_select :category_id, @grandchild_category_array,:id, :name, {selected:@grandchild_category.id,include_blank: "---"},{required: true}


            .detail--bland
              .content__header
                %h3 ブランド
                %span.notMust 任意
              = f.text_field :brand, placeholder: "例）シャネル"
            .detail--condition
              .content__header
                %h3 商品の状態
                %span 必須
              = f.select :condition, [["新品、未使用", 1], ["未使用に近い",2], ["目立った汚れなし", 3], ["やや汚れや傷あり", 4], ["傷や汚れ有り",5],["全体的に状態が悪い",6]],include_blank: "選択してください", class: "select"

        .content__4
          .items__delivery
            %h2 配送について
            .items__delivery--cost
              .content__header
                %h3 配送料の負担
                %span 必須
              = f.select :postage_payer, [["送料込み（出品者負担）", 1], ["着払い（購入者負担）",2]],include_blank: "選択してください", class: "select"

            .items__delivery--way
              .content__header
                %h3 配送方法
                %span 必須
              = f.select :postage_type, [["未定", 1], ["クロネコヤマト",2],["ゆうパック",3], ["ゆうメール", 4]],include_blank: "選択してください", class: "select"

            .items__delivery--place
              .content__header
                %h3 発送元の地域
                %span 必須
              = f.collection_select :prefecture_id, Prefecture.all, :id, :name, include_blank: "選択してください"

            .items__delivery--days
              .content__header
                %h3 発送までの日数
                %span 必須
              = f.select :preparation_day, [["１〜２日で発送", 1], ["２〜３日で発送",2],["４〜７日で発送",3]],include_blank: "選択してください", class: "select"

        .content__5
          .items__price
            %h2 価格（¥300〜¥9,999,999）
            .items__price--input
              .content__header
                %h3 販売価格
                %span 必須
              .items__price--input__money
                %p ¥
                = f.text_field :price, class: "price", id: "input__price"

        .form__btn
          = f.submit name:"submit", value: "更新する",  class: "form__btn--submit"
          =link_to root_path, class: "form__btn--back" do
            もどる
          %p 禁止されている行為および出品物を必ずご確認ください。偽ブランド品や盗品物などの販売は犯罪であり、法律により処罰される可能性があります。 また、出品をもちまして加盟店規約に同意したことになります。
  .bottom
    .link
      =link_to do
        プライバシーポリシー
      =link_to do
        メルカリ利用規約
      =link_to do
        特定商取引に関する表記
    .logo
      =link_to root_path do
        = image_tag "/logo-white.png",size: "200x60", alt: "visual-1"
      %p © FURIMA

app/views/items/index.html.haml
.wrapper
  =render "header"
  - breadcrumb :root
  = breadcrumbs separator: " &rsaquo; "
  .main
    .content
      .visual
        -# background-image
      .visual__comment
        .visual__comment--subtitle
          %h1 人生を変えるフリマアプリ
        .visual__comment--text
          %p FURIMAはかんたんに出品・購入できる
          %p フリマアプリです
        .visual__comment--btn
          = link_to do
            #apple
              = image_tag '/Download_on_the_App_Store_Badge_JP_blk_100317.png',height: "px", width: "150px", alt: 'apple'
          = link_to do
            #google
              = image_tag '/google-play-badge.png',height: "80px", width: "200px", alt: 'google'
    .introduction
      .title
        %h2 FURIMAが選ばれる３つの理由
      .lists
        %ul
          .list
            %li
              = image_tag "/pict-reason-01.jpg",size: "265x265", alt: "visual-1"
              %h3 3分ですぐ出品
              %p スマホで入力するだけで簡単に出品できる

            %li
              = image_tag "/pict-reason-02.jpg",size: "265x265", alt: "visual-1"
              %h3 シンプルで使いやすい
              %p めんどくさい入力は必要なく検索も購入もスムーズ！
            %li
              = image_tag "/pict-reason-03.jpg",size: "265x265", alt: "visual-1"
              %h3 手数料業界最安
              %p 最大３％でお得に出品＆購入！

    .content2
      .visual
        -# background-image
      .visual__comment
        .visual__comment--subtitle
          %h2 会員数日本一
        .visual__comment--text
          %p FURIMAはフリマアプリで最も人気。
          %p 出品・購入回数も業界最多です！
          %p 欲しかったあの商品に出会えるかもしれません。
        .visual__comment--btn
          = link_to do
            #apple
              = image_tag '/Download_on_the_App_Store_Badge_JP_blk_100317.png',height: "px", width: "150px", alt: 'apple'
          = link_to do
            #google
              = image_tag '/google-play-badge.png',height: "80px", width: "200px", alt: 'google'


    .introduction
      .title
        %h2 FURIMAの特徴
      .lists
        %ul
          .list
            %li
              = image_tag "/icon-01.png",size: "140x216", alt: "visual-1"
              %h3 簡単に売り買いができる
              %p スマホひとつで、いつでもどこでも簡単に出品・購入が可能！
            %li
              = image_tag "/icon-02.png",size: "140x216", alt: "visual-1"
              %h3 売上金は即日振り込みに対応
              %p 午前9時までに振込を依頼いただければ、翌日に指定の口座に入金いたします!
            %li
              = image_tag "/icon-03.png",size: "140x216", alt: "visual-1"
              %h3 様々な支払いに対応
              %p お支払いは、クレジットカードだけでなく、ポイントや売上金など多彩な方法があります。

    .pickup
      .pickup__category
        %h2 ピックアップカテゴリー
        %h3 新規投稿商品
        .pickup-list
          - @items.each do |item|
            = render partial: 'item', locals: {item: item}

      .pickup__brand
        %h2 ピックアップブランド
        %h3 アーカイブ
        .pickup-list
          - @brandItems.each do |item|
            = render partial: 'item', locals: {item: item}


    .content3
      .visual
        -# background-image
      .visual__comment
        #bottomVisual
          .visual__comment--text
            %p だれでもかんたん、人生を変えるフリマアプリ
          .visual__comment--subtitle
            %h2 今すぐ無料ダウンロード！
          .visual__comment--btn
            = link_to do
              #apple
                = image_tag '/Download_on_the_App_Store_Badge_JP_blk_100317.png',height: "px", width: "150px", alt: 'apple'
              = link_to do
                #google
                  = image_tag '/google-play-badge.png',height: "80px", width: "200px", alt: 'google'

  - if user_signed_in?
    .btn
      =link_to new_item_path do
        .linkBtn
          %p 出品する
          = image_tag '/icon_camera.png',height: "50px", width: "50px", alt: 'sell'

  = render "footer"

app/views/items/logout.html.haml
.main-page
  %main.container.clearfix
    .contents
      .logout
        .logout__container
          = link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'logout-btn’

app/views/items/mypage.html.haml
.main-page
  %main.container.clearfix
    .contents
      %section.mypage
        %figure
          .mypage__icon
            = image_tag 'member_photo_noimage_thumb.png', height: '60', width: '60', class: "mypage__icon__link"
          %h2.mypage__nickname
            ニックネーム
          .mypage__number
            .mypage__number--assess
              評価 ０
            .mypage__number--displays
              出品数 ０
      %section.mypage-container
        %ul.mypage-container__tabs
          %li.mypage-container__tabs--notice
            %h3
              = link_to "お知らせ", class: 'btn'
          %li.mypage-container__tabs--todo
            %h3
              = link_to "やることリスト", class: 'btn'
  
        .mypageContents
          %ul.mypageContentsList
            %li.mypageContentsList--link
              %figure
                .mypageContentsList--link__icon
                  = image_tag 'icon_brand.png', height: '48', width: '48', class: "mypage__tabs--content__link--icon"
                .mypageContentsList--link__body
                  .mypageContentsList--link__text もう購入しましたか？今なら"+20%還元"
            %li.mypageContentsList--link
              %figure
                .mypageContentsList--link__icon
                  = image_tag 'icon_brand.png', height: '48', width: '48', class: "mypage__tabs--content__link--icon"
                .mypageContentsList--link__body
                  .mypageContentsList--link__text 《出品するだけ》最大1,000円分のポイントをもらえる！キャンペーン詳細はこちら！
            %li.mypageContentsList--link
              %figure
                .mypageContentsList--link__icon
                  = image_tag 'icon_brand.png', height: '48', width: '48', class: "mypage__tabs--content__link--icon"
                .mypageContentsList--link__body
                  .mypageContentsList--link__text キャッシュレス決済で商品を買うとP1,500もらえる！
            %li.mypageContentsList--link
              %figure
                .mypageContentsList--link__icon
                  = image_tag 'icon_brand.png', height: '48', width: '48', class: "mypage__tabs--content__link--icon"
                .mypageContentsList--link__body
                  .mypageContentsList--link__text 「本人確認後」＋「街のお店でのお買い物」でもれなくP1,000をプレゼント！
            %li.mypageContentsList--link
              %figure
                .mypageContentsList--link__icon
                  = image_tag 'icon_brand.png', height: '48', width: '48', class: "mypage__tabs--content__link--icon"
                .mypageContentsList--link__body
                  .mypageContentsList--link__text フリマで買うと最大でP5,000+P1,000もらえる！事前準備はこちら
            %li.mypageContentsList--display
              = link_to "一覧を見る", class: 'btn'

      %section.Purchased
        %h2.Purchased__head 購入した商品
        %ul.purchased-tabs
          %li.trade
            %h3
              取引中
          %li
            %h3
              過去の取引
        .tab-contents
          %ul.tab-contents__now
            %li.tab-contents__notfound 取引中の商品がありません

app/views/items/show.html.haml
.wrapper
  = render "header"
  .sale-item-page
    -# カテゴリのナビゲーター
    .category-nav
      %ul
        %li
          = link_to "FURIMA", "#"
        %li
          %i.fa.fa-angle-right
        %li
          = link_to @item.category.root.name, "#"
        %li
          %i.fa.fa-angle-right
        %li
          = link_to @item.category.parent.name, "#"
        %li
          %i.fa.fa-angle-right
        %li
          = link_to @item.category.name, "#"
        %li
          %i.fa.fa-angle-right
        %li
          = link_to @item.name, "#", class: "current-page"
      
    .sale-item__container
      %h2.item-name
        = @item.name
      .item-image-box
        .item-image-box__main
          = image_tag @item.images.first.image_url.url,class: "item-image-box__main--image"
        %ul.item-image-thumbnail
          - @item.images.each do |image|
            %li.item-image-thumbnail__part
              = image_tag image.image_url.url, class:"item-image-thumbnail__part--mini-image"
           
      .item-price-box
        .item-price-box__price
          = "¥#{@item.price}"
        .item-price-box__detail
          %span.item-price-box__detail--tax
            (税込)
          %span.item-price-box__detail--postage
            - case @item.postage_payer
              - when 1
                = "送料込み"
              - when 2
                = "送料別"

      .item-content
        = @item.content
        
        <br/>
      -# 出品者以外がログイン時のみ閲覧可能
      - if user_signed_in? && current_user.id != @item.seller_id
        = link_to "購入する", confirm_item_path, class: "item-buy-link"
      -# ここまで

      .item-content
        %table
          %tbody
            %tr
              %th
                出品者
              %td
                = @seller.nickname
            %tr
              %th
                カテゴリー
              %td
                =link_to @item.category.root.name, "#"
                %br
                =link_to @item.category.parent.name, "#"
                %br
                =link_to @item.category.name, "#"
            %tr
              %th
                ブランド
              %td
                = @item.brand
            %tr
              %th
                商品の状態
              %td
                - case @item.condition
                  - when 1
                    = "新品、未使用"
                  - when 2
                    = "未使用に近い"
                  - when 3
                    = "目立った傷や汚れなし"
                  - when 4
                    = "やや傷や汚れあり"
                  - when 5
                    = "傷や汚れあり"
                  - when 6
                    = "全体的に状態が悪い"
            %tr
              %th
                配送方法
              %td
                -case @item.postage_type
                  - when 1
                    = "未定"
                  - when 2
                    = "クロネコヤマト"
                  - when 3
                    = "ゆうパック"
                  - when 4
                    = "ゆうメール"
          
            %tr
              %th
                配送料の負担
              %td
                - case @item.postage_payer
                  - when 1
                    = "送料込み(出品者負担)"
                  - when 2
                    = "着払い(購入者負担)"
            %tr
              %th
                発送元の地域
              %td
                =link_to "#" do
                  = @item.prefecture.name
            %tr
              %th
                発送日の目安
              %td
                - case @item.preparation_day
                  - when 1
                    = "1~2日で発送"
                  - when 2
                    = "2~3日で発送"
                  - when 3
                    = "4~7日で発送"
                
      -# 出品者以外がログイン時のみ閲覧可能
      - if user_signed_in? && current_user.id != @item.seller_id
        .item-menu
          %ul.item-menu__list
            %li.item-menu__list--like-btn
              %icon.fa.fa-star
              お気に入り 0
            %li.item-menu__list--report-btn
              = link_to "#" ,class:"report-link" do
                %icon.fa.fa-flag
                  不適切な商品の通報
      -# ここまで
    
    -# 出品者のみ閲覧可能
    - if user_signed_in? && current_user.id == @item.seller_id
      .exhibitor-menu-container 
        = link_to "商品を編集する",edit_item_path(@item), class: "exhibitor-menu-container__edit"
        %p or
        = link_to "この商品を削除する", item_path(@item), method: :delete, class: "exhibitor-menu-container__delete"
    -# ここまで

    -# ログイン時のみ閲覧可能（ログインしているユーザー全て）
    - if user_signed_in?
      .comment-container
        = form_with url: "#" do |f|
          = f.text_area :comment, class: "comment-inputbox"
          %p.itemnotice
            相手のことを考え丁寧なコメントを心がけましょう。
            %br
            不快な言葉遣いなどは利用制限や退会処分となることがあります。
            %br
          = button_tag type: "submit", class: "comment-submit-btn" do
            %icon.fa.fa-comment
            コメントする
    // ここまで

    %ul.item-links
      %li
        - if @item.id != @items.first.id
          = link_to item_path(@item.id - 1), class:"item-links__btn" do
            %icon.fa.fa-angle-left
            前の商品
      %li
        - if @item.id != @items.last.id
          = link_to item_path(@item.id + 1), class:"item-links__btn" do
            後ろの商品
            %icon.fa.fa-angle-right
    .more-items
      = link_to "#{@item.category.name}をもっと見る", "#", class: "more-items__link"
    
    .product-list
      = render partial:'item', collection: @relatedItems
  
  .content3
    .visual
    .visual__comment
      #bottomVisual
        .visual__comment--text
          %p だれでもかんたん、人生を変えるフリマアプリ
        .visual__comment--subtitle
          %h2 今すぐ無料ダウンロード！
        .visual__comment--btn
          = link_to do
            #apple
              = image_tag '/Download_on_the_App_Store_Badge_JP_blk_100317.png',height: "px", width: "150px", alt: 'apple'
            = link_to do
              #google
                = image_tag '/google-play-badge.png',height: "80px", width: "200px", alt: 'google'
  = render "footer"